Fix docker-compose error
There is a conflict between ports in docker-compose.yml and
docker-compose.override.yml which cause the following error as soon as
we use a docker-compose command such as:

  $ docker-compose ps
  Traceback (most recent call last):
    File "/usr/local/bin/docker-compose", line 11, in <module>
      sys.exit(main())
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/cli/main.py", line 68, in main
      command()
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/cli/main.py", line 115, in perform_command
      project = project_from_options('.', options)
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/cli/command.py", line 37, in project_from_options
      override_dir=options.get('--project-directory'),
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/cli/command.py", line 91, in get_project
      config_data = config.load(config_details)
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/config/config.py", line 379, in load
      service_dicts = load_services(config_details, main_file)
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/config/config.py", line 475, in load_services
      service_config = merge_services(service_config, next_config)
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/config/config.py", line 466, in merge_services
      for name in all_service_names
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/config/config.py", line 466, in <dictcomp>
      for name in all_service_names
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/config/config.py", line 853, in merge_service_dicts_from_files
      new_service = merge_service_dicts(base, override, version)
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/config/config.py", line 929, in merge_service_dicts
      merge_ports(md, base, override)
    File "/home/gbaconnier/.local/lib/python3.5/site-packages/compose/config/config.py", line 962, in merge_ports
      md[field] = [item for item in sorted(merged.values())]
  TypeError: unorderable types: int() < NoneType()